[tool.poetry]
name = "python-interview-prep"
version = "0.1.0"
description = "Hands-on materials for knowledge refreshing and interview preparation."
authors = ["Ivan Prytula <ivanprytula87@gmail.com>"]
license = "MIT"
readme = "README.md"

